# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"*\n\x10GenerateResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t2W\n\nInferencer\x12I\n\x0cGenerateText\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse\"\x00\x42@Z>github.com/lao-tseu-is-alive/go-cloud-grpc-client-ai/inferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/lao-tseu-is-alive/go-cloud-grpc-client-ai/inference'
  _globals['_GENERATEREQUEST']._serialized_start=30
  _globals['_GENERATEREQUEST']._serialized_end=63
  _globals['_GENERATERESPONSE']._serialized_start=65
  _globals['_GENERATERESPONSE']._serialized_end=107
  _globals['_INFERENCER']._serialized_start=109
  _globals['_INFERENCER']._serialized_end=196
# @@protoc_insertion_point(module_scope)
