[project]
name = "python-grpc-server-langchain-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.75.1",
    "grpcio-tools>=1.75.1",
]
